# Generated by Django 4.2.5 on 2023-10-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('view', models.CharField(max_length=10)),
                ('key_points', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_num', models.PositiveBigIntegerField()),
                ('file_dir', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('source_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='annotate.sourcedata')),
            ],
        ),
        migrations.CreateModel(
            name='Polygons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('LV', 'Left Ventricle'), ('LVM', 'Left Ventricular Myocardium'), ('LA', 'Left Atrium'), ('LAM', 'Left Atrial Myocardium'), ('other', 'other')], max_length=10)),
                ('points', models.JSONField()),
                ('annotation_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotate.annotationdata')),
            ],
            options={
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('research_id', models.CharField(max_length=100)),
                ('frame_num_from_ori', models.PositiveBigIntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('source_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotate.sourcedata')),
            ],
        ),
        migrations.AddField(
            model_name='annotationdata',
            name='image_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='annotate.imagedata'),
        ),
    ]
