# Generated by Django 4.2.5 on 2023-10-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0002_task_stop_frame'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagedata',
            options={'ordering': ['file_name']},
        ),
    ]
